### ISSUE TITLE
Liquid-like animated pagination dots 

### ISSUE THREAD

**Issue by Angelk90** [weahforsage/react-native-animated-pagination-dots#1]
Hi @weahforsage , it would be possible to add the following feature to the module.

![](https://camo.githubusercontent.com/975cf89ffd480ddd2cf7d0dddbe0010ef757f780af7c446aa75125e1fcbd450a/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f37323533352f73637265656e73686f74732f323432393033362f706167655f7363726f6c6c696e67322e676966)

![](https://camo.githubusercontent.com/f65b0c8fc3b92a0bf284c4ec409becf9b669949439be9e6c923133678bd3156d/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f32652f36302f39332f32653630393366346364303434316631373435393537336133636266613236622e676966)

**Comment by weahforsage** [comment]
I'm working on it, keep in touch :)

**Comment by Angelk90** [comment]
@weahforsage : Are there any news?

**Comment by weahforsage** [comment]
https://github.com/weahforsage/react-native-animated-pagination-dots/commit/047067f4bcb9f6983c2814fa11f06b84cad92f27

**Comment by weahforsage** [comment]
Added Liquid Like Indicator, And btw this one is closest one I can get. Hope you like it. 🎉🎈
https://github.com/weahforsage/react-native-animated-pagination-dots/commit/047067f4bcb9f6983c2814fa11f06b84cad92f27

**Comment by Angelk90** [comment]
Hi @weahforsage , in the case of the liquid-like, it would be possible to make that when passing from one dots to another dots instead of having square corners it has rounded corners, as seen in image2.

**Comment by weahforsage** [comment]
> Hi @weahforsage , in the case of the liquid-like, it would be possible to make that when passing from one dots to another dots instead of having square corners it has rounded corners, as seen in image2.

Yes possible but unfortunately I can't. Just cant find way to do this.

**Comment by weahforsage** [comment]
> Hi @weahforsage , in the case of the liquid-like, it would be possible to make that when passing from one dots to another dots instead of having square corners it has rounded corners, as seen in image2.


![ezgif com-gif-maker](https://user-images.githubusercontent.com/33711456/105577498-09371280-5db5-11eb-9308-6f1a715df31b.gif)
Actually this one is closest one I can get.

**Comment by Angelk90** [comment]
@weahforsage : You can put it on snack.expo.io, examples so I can try it?

**Comment by weahforsage** [comment]
> @weahforsage : You can put it on snack.expo.io, examples so I can try it?

690c932
Liquid Like Animation Added. Dependency: RNSVG
