### ISSUE TITLE
Error: Invariant Violation: requireNativeComponent: "RNSVGLine" was not found in the UIManager.

### ISSUE THREAD

**Issue by redlac** [weahforsage/react-native-animated-pagination-dots#15]
Hello, 

I received the following error after trying to implement the "Button Navigation Example": 
`Invariant Violation: requireNativeComponent: "RNSVGLine" was not found in the UIManager.`

**Comment by redlac** [comment]
Solved by installing [react-native-svg](https://github.com/react-native-svg/react-native-svg) and running Clean & Build on the Android project.

**Comment by alex-fournier** [comment]
I had the same problem. I am with Expo SDK 44 and the only compatible version of `react-native-svg` is `v12.1.1`.
So I fixed it by forcing the version of `react-native-svg` in my `package.json`:

```json
{
  "resolutions": {
    "react-native-svg": "12.1.1"
  }
}
```

**Comment by weahforsage** [comment]
Merged https://github.com/weahforsage/react-native-animated-pagination-dots/pull/20/commits/8992d86edf69fecad5d8f6f4813d7fc64bc31138
