### ISSUE TITLE
Callback click dots

### ISSUE THREAD

**Issue by Angelk90** [weahforsage/react-native-animated-pagination-dots#2]
Hi @weahforsage , 
would it be possible to make it possible to click on the dots and receive I don't know, index of the clicked dots?

**Comment by weahforsage** [comment]
Yeah possible, noted.

**Comment by Angelk90** [comment]
@weahforsage : Are there any news?

**Comment by Angelk90** [comment]
@weahforsage : Are there any news?

**Comment by XxQuickSilverZz** [comment]
what a bad libary..... avoid the timewaste guys!
