### ISSUE TITLE
Problem when the device rotates

### ISSUE THREAD

**Issue by Angelk90** [weahforsage/react-native-animated-pagination-dots#3]
Hi @weahforsage , 
it seems that when the device rotates or is rotated, the pagination no longer works, I also tried with your example, but it gives problems.

I don't know if the problem is: `const {width} = Dimensions.get('screen');`, that when the device rotates it doesn't update its dimensions or anything.

**Comment by weahforsage** [comment]
I should've test on landscape. I'll add it later

**Comment by Angelk90** [comment]
@weahforsage : Are there any news?

**Comment by Angelk90** [comment]
@weahforsage : Are there any news?

**Comment by weahforsage** [comment]
> @weahforsage : Are there any news?
> 
> 

This one would take a little bit time, I cannot give you any ETA at the moment.

**Comment by fjmorant** [comment]
@weahforsage created a PR to solve this issue https://github.com/weahforsage/react-native-animated-pagination-dots/pull/7

**Comment by weahforsage** [comment]
> @weahforsage created a PR to solve this issue https://github.com/weahforsage/react-native-animated-pagination-dots/pull/7

I'll review that as soon as I can. Thank you for contributing.

**Comment by fjmorant** [comment]
@weahforsage nice, we are using this branch in our app and works all well if you need any help in understanding the changes please give me a shout

**Comment by fjmorant** [comment]
@weahforsage @redk1 any news about merging and having this PR in the main repo? https://github.com/weahforsage/react-native-animated-pagination-dots/pull/7 thx

**Comment by weahforsage** [comment]
> @weahforsage @redk1 any news about merging and having this PR in the main repo? #7 thx

Merged  fb2f553.
