### ISSUE TITLE
SlidingBorder change size

### ISSUE THREAD

**Issue by Angelk90** [weahforsage/react-native-animated-pagination-dots#6]
Hi @weahforsage , it would be possible to do so instead of halving the dots, make the dots have the size that is passed and then everything else conforms to this.

See the image to understand.

Link: [https://snack.expo.io/pyTtLh2gp](snack)

<img width="282" alt="Schermata 2021-01-14 alle 17 32 25" src="https://user-images.githubusercontent.com/20476002/104619722-7dbfd200-568e-11eb-9ceb-38fca31d186b.png">

**Comment by weahforsage** [comment]
You can adjust by dotSize and borderPadding.
